project:
    name: 
        aws-event-driven-data-platform
    environment: 
        dev
  
s3:
    bucket: 
        event-platform-new
    layers:
        raw: 
            raw/
        validated:
            validated/user_events
            validated/payment_events
            validated/order_events
        rejected:
            rejected/
        silver:
            silver/user_events/
            silver/payment_events/
            silver/order_events/
        gold:
            gold/
            
data_generator_for_ingestion:
    allowed_extension: 
        json
    script:
        data_generator/generate_events.py
    schemas:
        data_generator/schemas
            - event_envelope_schema.json
            - file_container_schema.json
            - order_payload_schema.json
            - payment_payload_schema.json
            - user_payload_schema.json
            
iam:
    lambda_roles:
        role_name:
            - event-platform-lambda_role
            - lambda-secrets-manager-role
        policy_script:
            - infra/iam/lambda/lambda_execution_policy.json
            - infra/iam/lambda/lambda_secrets_manager_policy.json
    step_function_roles:
        role_name:
            - step_functions_for_validated_to_silver
            - step_functions_for_silver_to_gold
        policy_script:
            - infra/iam/lambda/sf_validated_to_silver_policy.json
            - infra/iam/lambda/sf_silver_to_gold_policy.json
    event_bridge_roles:
        role_name:
            - event_bridge_for_gold_to_validated_sf
            - event_bridge_for_silver_to_gold_sf
        policy_script:
            - infra/iam/lambda/eb_validated_to_silver_policy.json
            - infra/iam/lambda/eb_silver_to_gold_policy.json
    databricks_role:
        role_name:
            - databricks_aws_connection_role
        policy_script:
            - infra/iam/lambda/db_aws_connection_policy.json
            - infra/iam/lambda/db_aws_conection_trust_policy.json
            
lambda:
    raw_to_validated_or_rejected:
        function_name: 
            event_processing_function
        timeout_seconds: 
            30
        memory_mb: 
            1024
        trigger:
            sqs:
                event-platform-new
        trigger_type:
            event_source_mapping
        environment_variables:
            none
        iam_role:
            event-platform-lambda_role
        script:
            lambda/raw_to_validated_or_rejected/event_processing_function.py
            
    validated_to_silver:
        dataricks_silver_trigger:
            function_name: 
                databricks_silver_trigger_lambda
            timeout_seconds: 
                30
            memory_mb: 
                1024
            trigger:
                none
            trigger_type:
                none
            environment_variables:
                - DATABRICKS_HOST
                - SILVER_JOB_ID
                - SECRET_NAME
            iam_role:
                lambda-secrets-manager-role
            script:
                lambda/validated_to_silver/databricks_silver_trigger_lambda.py
                
        dataricks_silver_status:
            function_name: 
                databricks_silver_status_lambda
            timeout_seconds: 
                30
            memory_mb: 
                1024
            trigger:
                none
            trigger_type:
                none
            environment_variables:
                - DATABRICKS_HOST
                - SILVER_JOB_ID
                - SECRET_NAME
            iam_role:
                lambda-secrets-manager-role
            script:
                lambda/validated_to_silver/databricks_silver_status_lambda.py
                
    silver_to_gold:
        dataricks_gold_trigger:
            function_name: 
                databricks_gold_trigger_lambda
            timeout_seconds: 
                30
            memory_mb: 
                1024
            trigger:
                none
            trigger_type:
                none
            environment_variables:
                - DATABRICKS_HOST
                - GOLD_JOB_ID
                - SECRET_NAME
            iam_role:
                lambda-secrets-manager-role
            script:
                lambda/silver_to_gold/databricks_gold_trigger_lambda.py
                
        dataricks_gold_status:
            function_name: 
                databricks_silver_status_lambda
            timeout_seconds: 
                30
            memory_mb: 
                1024
            trigger:
                none
            trigger_type:
                none
            environment_variables:
                - DATABRICKS_HOST
                - GOLD_JOB_ID
                - SECRET_NAME
            iam_role:
                lambda-secrets-manager-role
            script:
                lambda/silver_to_gold/databricks_gold_status_lambda.py
            
dynamodb:
    table_name:
        event-platform-metadata
    partition_key:
        etag
    sort_key:
        None
    capacity_mode:
        on-demand
    global_secondary_index:
        None
    local_secondary_index:
        None
        
sqs:
    main_queue_for_validation:
        queue_name: 
            s3_to_validation_lambda
        visibility_timeout_seconds:
            30
        message_retention_period_days:
            4
        maximum_message_size:
            1024
        delivery_delay_seconds:
            0
        recieve_message_wait_time_seconds:
            0
        encryption:
            server-side-enncryption:
                enabled
        dead_letter_queue:
            enabled
            queue_name:
                arn:aws:sqs:<REGION>:<ACCOUNT NUMBER>:dlq-s3_to_validation_lambda
            maximum_retry_count:
                3
        access_policy:
            infra/sqs/s3_to_validation_lambda/s3_to_validation_lambda_policy.json
    
    dead_letter_queue_for_validation:
        queue_name: 
            dlq_for_s3_to_validation_lambda
        visibility_timeout_seconds:
            30
        message_retention_period_days:
            4
        maximum_message_size:
            1024
        delivery_delay_seconds:
            0
        recieve_message_wait_time_seconds:
            0
        encryption:
            server-side-enncryption:
                enabled
        redrive_allow_policy:
            enabled
            permission:
                by_queue
            queue_name:
                arn:aws:sqs:<REGION>:<ACCOUNT NUMBER>:s3_to_validation_lambda
        dead_letter_queue:
            diabled
        access_policy:
            infra/sqs/s3_to_validation_lambda/dlq_for_s3_to_validation_lambda_policy.json

  
    main_queue_for_processing_validated_to_step_functions:
        queue_name: 
            validation_lambda_to_step_functions
        visibility_timeout_seconds:
            360
        message_retention_period_days:
            4
        maximum_message_size:
            1024
        delivery_delay_seconds:
            0
        recieve_message_wait_time_seconds:
            0
        encryption:
            server-side-enncryption:
                enabled
        dead_letter_queue:
            enabled
            queue_name:
                arn:aws:sqs:<REGION>:<ACCOUNT NUMBER>:dlq_for_validation_lambda_to_step_functions
            maximum_retry_count:
                3
        access_policy:
            infra/sqs/validation_lambda_to_step_functions/validation_lambda_to_step_functions.json
    
    dead_letter_queue_for_processing_validated_to_step_functions:
        queue_name: 
            dlq_for_validation_lambda_to_step_functions
        visibility_timeout_seconds:
            30
        message_retention_period_days:
            4
        maximum_message_size:
            1024
        delivery_delay_seconds:
            0
        recieve_message_wait_time_seconds:
            0
        encryption:
            server-side-enncryption:
                enabled
        redrive_allow_policy:
            enabled
            permission:
                by_queue
            queue_name:
                arn:aws:sqs:<REGION>:<ACCOUNT NUMBER>:validation_lambda_to_step_functions
        dead_letter_queue:
            diabled
        access_policy:
            infra/sqs/validation_lambda_to_step_functions/dlq_for_validation_lambda_to_step_functions.json

step_functions:
    validated_to_silver:
        state_machine_name:
            validated_to_silver_state_machine
        graph:
            validated_to_silver_state_machine.png
        iam_role:
            step_functions_for_validated_to_silver
        script:
            step_functions/validated_to_silver_state_machine.json
            
    silver_to_gold:
        state_machine_name:
            silver_to_gold_state_machine
        graph:
            silver_to_gold_state_machine.png
        iam_role:
            step_functions_for_silver_to_gold
        script:
            step_functions/silver_to_gold_state_machine.json

eventbridge:
    validated_to_silver:
        type:
            eventbridge_schedule
        schedule_pattern:
            recurring_schedule
        schedule_type:
            rate_based_schedule
        rate_expression:
            rate(5, minutes)
        flexible_time_window:
            5 minutes
        target:
            aws_step_functions
        state_machine:
            validated_to_silver_state_machine
    silver_to_gold:
        type:
            eventbridge_schedule
        schedule_pattern:
            recurring_schedule
        schedule_type:
            rate_based_schedule
        rate_expression:
            rate(30, minutes)
        flexible_time_window:
            30 minutes
        target:
            aws_step_functions
        state_machine:
            silver_to_gold_state_machine
            
databricks:
    silver_and_bronze:
        mode:
            job_pipeline
        environment:
            notebook
        compute:
            serverless
        catalogue_name:
            demo
        schema:
            silver
        scripts:
            pyspark:
                databricks/silver/silver_transformation_job.py
            ddl:
                databricks/silver/silver_table_definition.sql
            optimization:
                databricks/silver/silver_maintenance_job.sql
            architecture_details:
                databricks/silver/silver_layer_performance architecture.md

    gold:
        mode:
            job_pipeline
        environment:
            notebook
        compute:
            serverless
        catalogue_name:
            demo
        schema:
            gold
        scripts:
            sql:
                databricks/gold/gold_transformation_job.sql
            ddl:
                databricks/gold/gold_table_definition.sql
            optimization:
                databricks/gold/gold_maintenance_job.sql